name: Generate Snake

# Controls when the action will run. This action runs every 6 hours and can also be triggered manually.
on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Generates the snake SVG
      - uses: Platane/snk@v1
        with:
          github_user_name: lamin-tamang
          svg_out_path: dist/github-snake.svg

      # List contents of the dist folder to verify SVG generation
      - name: List contents of dist folder
        run: ls -alh dist

      # Verify if the SVG file exists
      - name: Check SVG file existence
        run: |
          if [ -f dist/github-snake.svg ]; then echo "SVG file exists"; else echo "SVG file not found"; exit 1; fi

      # Commit and push the changes to the output branch
      - name: Commit and push changes to the output branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/github-snake.svg
          git commit -m "Update snake SVG"
          git push origin HEAD:output --force

      # Publish the generated snake graphics to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
