name: Generate Snake Animation

on:
  schedule:
    - cron: "* */12 * * *"  # Run every 12 hours
  workflow_dispatch:  # Trigger manually
  push:
    branches:
      - master  # Trigger on pushes to master

jobs:
  generate:
    permissions:
      contents: write  # Necessary permission to push changes
    runs-on: ubuntu-latest  # Runner environment
    timeout-minutes: 5  # Timeout for the job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Generate snake.svg
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.actor }}  # Use the GitHub actor to fetch the correct username

      # Step 3: Debugging - Check the contents of the dist directory
      - name: Check dist directory and file
        run: |
          echo "Listing contents of the dist directory:"
          ls -R dist  # List contents of the dist directory
          if test -f dist/snake.svg; then 
            echo "snake.svg exists"; 
          else 
            echo "snake.svg does not exist"; 
            exit 1; 
          fi

      # Step 4: Temporarily skip pushing to GitHub Pages to focus on generation
      # Uncomment below to enable pushing to the output branch after confirming file creation
      # - name: Push snake.svg to the output branch
      #   uses: crazy-max/ghaction-github-pages@v3.1.0
      #   with:
      #     target_branch: output  # Branch to push to
      #     build_dir: dist  # Directory containing the generated file
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
