name: Generate Snake

# Controls when the action will run. This action runs every 6 hours and can also be triggered manually.
on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2

      # Creates the 'dist' folder to store output if it doesn't exist.
      - name: Create dist directory
        run: mkdir -p dist

      # Generates the snake SVG
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: lamin-tamang
          svg_out_path: dist/github-snake.svg

      # Verify that the SVG file was created
      - name: Check SVG file existence
        run: |
          ls dist
          cat dist/github-snake.svg || echo "SVG file not found"

      # Commit and push the changes to the output branch
      - name: Commit and push changes to the output branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/github-snake.svg
          git commit -m "Update snake SVG"
          git push origin HEAD:output --force

      # Publishes the generated snake graphics to GitHub Pages.
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
