name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # This runs the workflow every 6 hours
  workflow_dispatch:  # This allows manual triggers

jobs:
  build:
    runs-on: ubuntu-latest  # The runner to use

    steps:
      - uses: actions/checkout@v2  # Checkout the repository

      - name: Generate the snake SVG (no GIF here)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: lamin-tamang
          svg_out_path: dist/github-snake.svg  # Where to save the SVG output

      # Push the changes to the output branch
      - name: Push changes
        uses: ad-m/github-push-action@master  # GitHub Push Action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the secret token here
          branch: output  # The branch to push to
          force: true  # Force push (be careful with this, it can overwrite changes)

      # Optionally, you can add additional steps like publishing the output to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Specify the target branch
          build_dir: dist  # Path to the directory containing the output
        env:
          MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Make sure token is available
