name: Generate Snake Animation

on:
  schedule:
    - cron: "* */12 * * *"  # Run every 12 hours
  workflow_dispatch:  # Trigger manually
  push:
    branches:
      - master  # Trigger on pushes to master

jobs:
  generate:
    permissions:
      contents: write  # Necessary permission to push changes
    runs-on: ubuntu-latest  # Runner environment
    timeout-minutes: 5  # Timeout for the job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Generate snake.svg
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.actor }}  # Use the GitHub actor to fetch the correct username

      # Step 3: Debugging - Check the contents of the dist directory
      - name: Check dist directory and file
        run: |
          echo "Listing contents of the dist directory:"
          ls -R  # List the contents of the entire repository
          if test -f dist/snake.svg; then 
            echo "snake.svg exists"; 
          else 
            echo "snake.svg does not exist"; 
            exit 1; 
          fi
